### ISSUE TITLE
Using .jump.json instructions missing

### ISSUE THREAD

**Issue by mrhillsman** [dropseed/jump#31]
Unfortunately as someone unfamiliar with the codebase of jump I am not able to easily understand how to use the required .jump.json file. Would it be possible to update the README.md in the root directory with instructions on how to use the .jump.json file appropriately?

**Comment by davegaeddert** [comment]
Thanks for pointing that out @mrhillsman. I added a little bit of info to the README. Let me know if there's anything else we can do to make it easier to get started! We mostly use this internally but think it's actually super useful...so I'm happy to try and make any changes to make it easier.
